
language: cpp

matrix:
  include:
    - os: linux
      env: DEPLOY_FILE=Muview.tar.gz
      env: APP_FILE=Muview2-x86_64.AppImage
      dist: xenial
      sudo: required
      compiler: clang
    - os: osx
      env: DEPLOY_FILE=Muview.dmg
      osx_image: xcode10.2
      sudo: required
      compiler: clang
addons:
  apt:
    sources:
    - sourceline: 'ppa:beineri/opt-qt-5.12.3-xenial' 
    packages:
    - qt512base
    - qt5123d
    - qt512tools
    - qt512x11extras
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install qt5;
      brew upgrade qt5;
      echo "Adding brewed Qt5 to path";
      export PATH=/usr/local/opt/qt5/bin:$PATH;
      qmake -v;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      echo "Before Install";
      sudo apt-get install -qq pkg-config fuse;
      sudo modprobe fuse;
      sudo chmod 666 /dev/fuse;
      sudo chown root:$USER /etc/fuse.conf;
      
      source /opt/qt512/bin/qt512-env.sh;
      which qmake;
      qmake -v;
  
      cd /home/travis/build;
      mkdir linuxdeployqt && cd linuxdeployqt;
      wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage -O linuxdeployqt;
      chmod a+x linuxdeployqt;
      export PATH=$PATH:/home/travis/build/linuxdeployqt;

      cd /home/travis/build;
      ( wget https://nixos.org/releases/patchelf/patchelf-0.9/patchelf-0.9.tar.bz2 && tar xf patchelf-0.9.tar.bz2);
      ( cd patchelf-0.9/ && ./configure --prefix=$HOME/patchelf && make && make install && cd ..);
      export PATH=$PATH:$HOME/patchelf/bin;
      
      cd /home/travis/build;
      mkdir appimagetool && cd appimagetool;
      wget https://github.com/probonopd/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool;
      chmod a+x appimagetool;
      export PATH=$PATH:/home/travis/build/appimagetool;
      
    fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "Preparing to deploy Muview2";
      bash deploy/deployMacOSX.sh;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cd /home/travis/build/grahamrow/Muview2;
      bash deploy/deployLinux_travis.sh;
    fi
deploy:
  provider: releases
  api_key:
    secure: WaoteXAP3GvNQh6rtIpTQG9oJd0QP4nrzQ+CtQxGH/u6aypK+YiaPRxoUlWDfjW3J7xjgMVRmZTV3DgxsSjV+1YgJav6XeS+ek/ZbKBqW/gqjmeSJflDt/fBsqXXaiSm98r1xVOsP1E0C4zq28ps8laSBSKL8iOKRgJ2i6Zc6hG5z3x8Y6kMBHWpTa68O8oBVPBO0tRKazML4XfoZ9VZswkFlmE4lEJtnuJagfUdFERzHCNmSazKF3HJVxLyDxxsBrjqcjIjHrJl3ySXzvXlTw/gRbRq/5rt55yJ2zOE4ToyIBhilWwWmIdreuiY4QbKHNDlbnHwQyzuewtxeH/U1lBzb0QhMMamhHweX1LxcQM0xopWGVcIHxae5BkInpQqKsrjVIrPFEVHGrgZJkofdt6fHcohLusyo5/PY3E8S6tExRd9DFuZpbuQjCLy+RWTsWhUVINh4geZrwFnaH0yqqo+8mqfgJwPQ07vN77HdLZ01bcvrpMvgNjtyt6dggAIQeQbc3LmBBFdENArTxTrIPQsFePZ1+IMaXW0GIPPMRthity9/yeMGUro8lzIYvSMWhtFTDDJs0Y7LyKiCXQ0AibDOTrShQRMsqz4+/lrUy9JU8zJBV81RGplu7OeMcVuMl8tphy8lVq4gUfW3k9VsY8cLjKTUesDaFqCgOcka5I=
  file: $DEPLOY_FILE
  skip_cleanup: true
  on:
    repo: grahamrow/Muview2
    tags: true