#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

environment:
  QT5: C:\Qt\5.12.2\msvc2017_64

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  - set PATH=%QT5%\bin;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

# clone directory
clone_folder: C:\dev\Muview2

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# scripts to run before build
before_build:
  - cd C:\dev\Muview2
  - mkdir Muview

# to run your custom scripts instead of automatic MSBuild
build_script:
  - qmake.exe -r -config release
  - nmake.exe
  - move source\muview.exe Muview\Muview.exe
  - windeployqt.exe Muview\Muview.exe

# scripts to run after build
after_build:
  - 7z a Muview.7z Muview

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'Muview.7z'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
    provider: GitHub
    auth_token:
      secure: d2MC+YJVRE4Fk2vgIEB+6i6b7w304DMoHMA/ILIATfQPJXYBUslAT5jgEYrPX/2kFG2swKx20gmQobhwvuV1qbKkGCjWxwh/DDZGtDaHE23Lc9buOV6T8j81+/dbKXBDMd++8WuK7inxjbiIU33K3XlZQ8rWhoVGwmUi7iRNySwM+3ehUyELvDFUl0ry6J1VgTYMEipPWQyXDun5kn2pChm0HLrwR3bqywigAsVzpZRedVhKSDbuaXvi1DXB5ASXLEA8qgSjmso+ZywqSNlJx3sd8QPMBm+pi77ViFk0dqMEcm+AhU6fUyFNnxXgcIwt6+3j2D8mys6GY2l72KnkqIVqfJMpuQxAwtvkOZrSL/NwMSZAauzz3E93AcOmSRaafrLlMdkhvOCGJ6hq7YmeE4YZF7AfYZ9WRUiYWCt8O2HX1ls0LLBYvrWnZqKNdcksWLSY83Sf21R6J7STJje/s7IC5d76GTq4E+3HrvVIphk5akPL6N5Ke4cuaTK333DxdCU/taQW7jM13hhnFy1byY3Vu48UVSbFuU+zsl9TBiHoYcjY5kwOGs41Bu5hKjXlPYw36EKpXqMdl4J3vWHHx9aRY5z5rMOsEe87gPAkCjpt3vGx2VkBJ0aiIZ1Bs6mYHwSSAlkaWINQ6cC/Fn6Uc6GL47VvA0jFwrX9+okoe/Y=
    artifact: Muview.7z
    draft:      true
    prerelease: false
    on:
      appveyor_repo_tag: true       # deploy on tag push only
