#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

environment:
  QT5: C:\Qt\5.7\msvc2015_64

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  - set PATH=%QT5%\bin;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

# clone directory
clone_folder: C:\dev\Muview2

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# scripts to run before build
before_build:
  - cd C:\dev\Muview2
  - mkdir Muview

# to run your custom scripts instead of automatic MSBuild
build_script:
  - qmake.exe -r -config release
  - nmake.exe
  - move source\muview.exe Muview\Muview.exe
  - windeployqt.exe Muview\Muview.exe

# scripts to run after build
after_build:
  - 7z a Muview.7z Muview

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'Muview.7z'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
    provider: GitHub
    auth_token:
      secure: 4m39FfOSSP2sZRdJ1hhC+UV00MzZr1ZVoLjWqbjRfM22tTleeSNxURJAbsKliImF
    artifact: Muview.7z
    draft:      false
    prerelease: false
    on:
      appveyor_repo_tag: true       # deploy on tag push only
